sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: VgJyBIr32Au6Sgymg/Za7RsceMvdQj16ZTkq6prig36cq1t7H3RHaWq/mkvDAzRQ5VHGs/GC83+wnonEbwOAqj335aVPgu5c/k87XkzLRaJ/Y28ahkIfg/PCOTaaHDESV7gIPpYjkUiEUu9AwA9t5iQi5gid5L5eH6D1rPrb1blezJuTi99vKl7Kyhsq14VfW5Wp+Q36a83wofNh9m+InK0lZQLFSq//Hh/y/7DbUS1ngaH7OQ8FHj4Gt6Gs7PjKCLD7D+ReGIOHwSyuHtzof6Nw0WQGmnNnpe414plJgxYby7U35qIvDAgj0VwIlbLqaCAOqJyNjfth3g+lBb7bBNZG2xgOB+Wq6PnRSKppx3DsME5WS0vuYzc3GnRTTrtAuQW1/WXSqyDdj15Qt1LZEK8RENDR/WVhLGzz1bGmjunHKtZEoVpV4vlIZHmY+Tq2v6xsWunC6MnbOgJxPlBTLct434UDkUGyC9ltp2DM46mABUGjQ6PBHLiWQ56uzRxA5g36XzU1PzOfVdjK0/ALm5dHGobdEu9Nh+GH9EZywC4OMwr0QQ6Rx4N1RoETNhc1+uA8Tz6NFNVt53nMnwhm6U3eajog2mnjo7Le5YWqwUqc0LWX8uC52YZF3pErdOoHGut8e4QqlLZKV9SJTCRr/4zhuE7sI1F3Qxg0bmdjCsA=
